//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMPS5101.Wcf51011 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Wcf51011.IService51011")]
    public interface IService51011 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService51011/UmpTaskOperation", ReplyAction="http://tempuri.org/IService51011/UmpTaskOperationResponse")]
        VoiceCyber.UMP.Communications.WebReturn UmpTaskOperation(VoiceCyber.UMP.Communications.WebRequest webRequest);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService51011Channel : UMPS5101.Wcf51011.IService51011, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service51011Client : System.ServiceModel.ClientBase<UMPS5101.Wcf51011.IService51011>, UMPS5101.Wcf51011.IService51011 {
        
        public Service51011Client() {
        }
        
        public Service51011Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service51011Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service51011Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service51011Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public VoiceCyber.UMP.Communications.WebReturn UmpTaskOperation(VoiceCyber.UMP.Communications.WebRequest webRequest) {
            return base.Channel.UmpTaskOperation(webRequest);
        }
    }
}
