//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMPS3601.Wcf36011 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Wcf36011.IService36011")]
    public interface IService36011 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService36011/UmpTaskOperation", ReplyAction="http://tempuri.org/IService36011/UmpTaskOperationResponse")]
        VoiceCyber.UMP.Communications.WebReturn UmpTaskOperation(VoiceCyber.UMP.Communications.WebRequest webRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService36011/UmpUpOperation", ReplyAction="http://tempuri.org/IService36011/UmpUpOperationResponse")]
        VoiceCyber.UMP.Communications.WebReturn UmpUpOperation(Common3601.UpRequest upRequest);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService36011Channel : UMPS3601.Wcf36011.IService36011, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service36011Client : System.ServiceModel.ClientBase<UMPS3601.Wcf36011.IService36011>, UMPS3601.Wcf36011.IService36011 {
        
        public Service36011Client() {
        }
        
        public Service36011Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service36011Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service36011Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service36011Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public VoiceCyber.UMP.Communications.WebReturn UmpTaskOperation(VoiceCyber.UMP.Communications.WebRequest webRequest) {
            return base.Channel.UmpTaskOperation(webRequest);
        }
        
        public VoiceCyber.UMP.Communications.WebReturn UmpUpOperation(Common3601.UpRequest upRequest) {
            return base.Channel.UmpUpOperation(upRequest);
        }
    }
}
