//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMPS3105.Wcf31051 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Wcf31051.IService31051")]
    public interface IService31051 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService31051/UMPTaskOperation", ReplyAction="http://tempuri.org/IService31051/UMPTaskOperationResponse")]
        VoiceCyber.UMP.Communications.WebReturn UMPTaskOperation(VoiceCyber.UMP.Communications.WebRequest webRequest);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService31051Channel : UMPS3105.Wcf31051.IService31051, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service31051Client : System.ServiceModel.ClientBase<UMPS3105.Wcf31051.IService31051>, UMPS3105.Wcf31051.IService31051 {
        
        public Service31051Client() {
        }
        
        public Service31051Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service31051Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service31051Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service31051Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public VoiceCyber.UMP.Communications.WebReturn UMPTaskOperation(VoiceCyber.UMP.Communications.WebRequest webRequest) {
            return base.Channel.UMPTaskOperation(webRequest);
        }
    }
}
