create table T_51_009_00000
(
  c001 NUMBER(20) not null,
  c002 NUMBER(20) not null,
  c003 VARCHAR2(64) not null,
  c004 VARCHAR2(5) not null,
  c005 NUMBER(20) not null,
  c006 NUMBER(20) not null,
  c007 NVARCHAR2(225) not null,
  c008 NVARCHAR2(255) not null,
  c009 NUMBER(20) not null,
  c010 NUMBER(20) not null,
  c011 NUMBER(20) not null,
  c012 NUMBER(20) not null,
  c013 NUMBER(20) not null,
  c014 NVARCHAR2(128),
  c015 NVARCHAR2(32),
  c016 NVARCHAR2(128),
  c017 CHAR(1),
  constraint PK_51_009 primary key (C001, C005, C007, C008)
);
