create table T_21_011_00000
(
  c001 NUMBER(20) default 0 not null,
  c002 VARCHAR2(1024) not null,
  c003 NVARCHAR2(1024),
  c004 CHAR(1) default 0 not null,
  c005 NUMBER(20) default 0 not null,
  c006 NUMBER(20) default 0 not null,
  c007 VARCHAR2(1024),
  c008 NUMBER(5) default 0,
  c009 NUMBER(11) default 0,
  c010 NUMBER(11) default 0,
  c011 VARCHAR2(1024),
  c012 NUMBER(20) default 0,
  c013 NUMBER(20) default 0,
  c014 NUMBER(20) default 0,
  c015 NUMBER(20) default 0,
  c016 NUMBER(20) default 0,
  constraint PK_21_011 primary key (C001)
);