create table T_51_007_00000
(
  c001 NUMBER(20) not null,
  c002 NVARCHAR2(256) not null,
  c003 CHAR(1) default 0,
  c004 DATE not null,
  c005 DATE not null,
  c006 NUMBER(20) not null,
  c007 NVARCHAR2(1024) not null,
  c008 CHAR(1) default 0,
  c009 DATE,
  c010 DATE,
  c011 NUMBER(20),
  c012 NVARCHAR2(1024),
  c013 DATE,
  c014 DATE,
  c015 NUMBER(20),
  c016 NVARCHAR2(1024),
  c017 DATE,
  c018 DATE,
  c019 NUMBER(20),
  c020 NVARCHAR2(1024),
  constraint PK_51_007 primary key (C001)
);
