//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMPS3105.Wcf31031 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Wcf31031.IService31031")]
    public interface IService31031 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService31031/UMPTaskOperation", ReplyAction="http://tempuri.org/IService31031/UMPTaskOperationResponse")]
        VoiceCyber.UMP.Communications.WebReturn UMPTaskOperation(VoiceCyber.UMP.Communications.WebRequest webRequest);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService31031Channel : UMPS3105.Wcf31031.IService31031, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service31031Client : System.ServiceModel.ClientBase<UMPS3105.Wcf31031.IService31031>, UMPS3105.Wcf31031.IService31031 {
        
        public Service31031Client() {
        }
        
        public Service31031Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service31031Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service31031Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service31031Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public VoiceCyber.UMP.Communications.WebReturn UMPTaskOperation(VoiceCyber.UMP.Communications.WebRequest webRequest) {
            return base.Channel.UMPTaskOperation(webRequest);
        }
    }
}
