//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMPS2101.Wcf11901 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Wcf11901.IService11901")]
    public interface IService11901 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService11901/OperationMethodA", ReplyAction="http://tempuri.org/IService11901/OperationMethodAResponse")]
        VoiceCyber.UMP.Controls.Wcf11901.OperationDataArgs OperationMethodA(int AIntOperationID, string[] AListStringArgs);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService11901Channel : UMPS2101.Wcf11901.IService11901, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service11901Client : System.ServiceModel.ClientBase<UMPS2101.Wcf11901.IService11901>, UMPS2101.Wcf11901.IService11901 {
        
        public Service11901Client() {
        }
        
        public Service11901Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service11901Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service11901Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service11901Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public VoiceCyber.UMP.Controls.Wcf11901.OperationDataArgs OperationMethodA(int AIntOperationID, string[] AListStringArgs) {
            return base.Channel.OperationMethodA(AIntOperationID, AListStringArgs);
        }
    }
}
