//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMPS3107.Wcf31071 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Wcf31071.IService31071")]
    public interface IService31071 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService31071/UMPTaskOperation", ReplyAction="http://tempuri.org/IService31071/UMPTaskOperationResponse")]
        VoiceCyber.UMP.Communications.WebReturn UMPTaskOperation(VoiceCyber.UMP.Communications.WebRequest webRequest);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService31071Channel : UMPS3107.Wcf31071.IService31071, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service31071Client : System.ServiceModel.ClientBase<UMPS3107.Wcf31071.IService31071>, UMPS3107.Wcf31071.IService31071 {
        
        public Service31071Client() {
        }
        
        public Service31071Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service31071Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service31071Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service31071Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public VoiceCyber.UMP.Communications.WebReturn UMPTaskOperation(VoiceCyber.UMP.Communications.WebRequest webRequest) {
            return base.Channel.UMPTaskOperation(webRequest);
        }
    }
}
