CREATE TABLE [dbo].[T_21_011_00000](
	[C001] [bigint] NOT NULL,
	[C002] [varchar](1024) NOT NULL,
	[C003] [nvarchar](1024) NULL,
	[C004] [char](1) NOT NULL,
	[C005] [bigint] NOT NULL,
	[C006] [bigint] NOT NULL,
	[C007] [varchar](1024) NULL,
	[C008] [smallint] NULL,
	[C009] [int] NULL,
	[C010] [int] NULL,
	[C011] [varchar](1024) NULL,
	[C012] [bigint] NULL,
	[C013] [bigint] NULL,
	[C014] [bigint] NULL,
	[C015] [bigint] NULL,
	[C016] [bigint] NULL,
 CONSTRAINT [PK__21_011_00000] PRIMARY KEY CLUSTERED 
(
	[C001] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];