CREATE TABLE [dbo].[T_51_006_00000](
	[C001] [bigint] NOT NULL,
	[C002] [nvarchar](20) NOT NULL,
	[C003] [varchar](512) NOT NULL,
	[C004] [nvarchar](1024) NULL,
	[C005] [char](1) NULL,
	[C006] [datetime] NOT NULL,
	[C007] [datetime] NOT NULL,
	[C008] [bigint] NOT NULL,
	[C009] [nvarchar](1024) NOT NULL,
	[C010] [char](1) NULL,
	[C011] [datetime] NULL,
	[C012] [datetime] NULL,
	[C013] [bigint] NULL,
	[C014] [nvarchar](1024) NULL,
	[C015] [datetime] NULL,
	[C016] [datetime] NULL,
	[C017] [bigint] NULL,
	[C018] [nvarchar](1024) NULL,
	[C019] [datetime] NULL,
	[C020] [datetime] NULL,
	[C021] [bigint] NULL,
	[C022] [nvarchar](1024) NULL,
 CONSTRAINT [SYS_C00115725_00000] PRIMARY KEY CLUSTERED 
(
	[C001] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];