CREATE TABLE [dbo].[T_51_007_00000](
	[C001] [bigint] NOT NULL,
	[C002] [nvarchar](256) NOT NULL,
	[C003] [char](1) NULL,
	[C004] [datetime] NOT NULL,
	[C005] [datetime] NOT NULL,
	[C006] [bigint] NOT NULL,
	[C007] [nvarchar](1024) NOT NULL,
	[C008] [char](1) NULL,
	[C009] [datetime] NULL,
	[C010] [datetime] NULL,
	[C011] [bigint] NULL,
	[C012] [nvarchar](1024) NULL,
	[C013] [datetime] NULL,
	[C014] [datetime] NULL,
	[C015] [bigint] NULL,
	[C016] [nvarchar](1024) NULL,
	[C017] [datetime] NULL,
	[C018] [datetime] NULL,
	[C019] [bigint] NULL,
	[C020] [nvarchar](1024) NULL,
 CONSTRAINT [SYS_C00115733_00000] PRIMARY KEY CLUSTERED 
(
	[C001] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];