--2016.9.9  YOUNG
alter table T_21_001 add c084 BIGINT     default 0 not null;
alter table T_21_001 add c091 SMALLINT   default 8 not null;
alter table T_21_001 add c092 SMALLINT   default 3 not null;
alter table T_21_001 add c093 SMALLINT   default 2 not null;
alter table T_21_001 add c094 INT        default 0;
alter table T_21_001 add c095 SMALLINT   default 0;


alter table T_21_001_00000 add c084 BIGINT     default 0 not null;
alter table T_21_001_00000 add c091 SMALLINT   default 8 not null;
alter table T_21_001_00000 add c092 SMALLINT   default 3 not null;
alter table T_21_001_00000 add c093 SMALLINT   default 2 not null;
alter table T_21_001_00000 add c094 INT        default 0;
alter table T_21_001_00000 add c095 SMALLINT   default 0;