--2016.9.9  YOUNG
alter table T_21_001 add c084 number(20)  default 0 not null;
alter table T_21_001 add c091 number(5)   default 8 not null;
alter table T_21_001 add c092 number(5)   default 3 not null;
alter table T_21_001 add c093 number(5)   default 2 not null;


alter table T_21_001_00000 add c084 number(20)  default 0 not null;
alter table T_21_001_00000 add c091 number(5)   default 8 not null;
alter table T_21_001_00000 add c092 number(5)   default 3 not null;
alter table T_21_001_00000 add c093 number(5)   default 2 not null;