//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMPS3106.Wcf31061 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Wcf31061.IService31061")]
    public interface IService31061 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService31061/UMPTreeOperation", ReplyAction="http://tempuri.org/IService31061/UMPTreeOperationResponse")]
        VoiceCyber.UMP.Communications.WebReturn UMPTreeOperation(VoiceCyber.UMP.Communications.WebRequest webRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService31061/UMPUpOperation", ReplyAction="http://tempuri.org/IService31061/UMPUpOperationResponse")]
        VoiceCyber.UMP.Communications.WebReturn UMPUpOperation(Common3106.UpRequest upRequest);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService31061Channel : UMPS3106.Wcf31061.IService31061, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service31061Client : System.ServiceModel.ClientBase<UMPS3106.Wcf31061.IService31061>, UMPS3106.Wcf31061.IService31061 {
        
        public Service31061Client() {
        }
        
        public Service31061Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service31061Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service31061Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service31061Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public VoiceCyber.UMP.Communications.WebReturn UMPTreeOperation(VoiceCyber.UMP.Communications.WebRequest webRequest) {
            return base.Channel.UMPTreeOperation(webRequest);
        }
        
        public VoiceCyber.UMP.Communications.WebReturn UMPUpOperation(Common3106.UpRequest upRequest) {
            return base.Channel.UMPUpOperation(upRequest);
        }
    }
}
