CREATE OR REPLACE FUNCTION F_BASIC_ISDATE(AStrDate VARCHAR2)
   RETURN NUMBER
AS  --是否是日期判断
   LDateConvert   DATE;
BEGIN
   LDateConvert := TO_DATE (AStrDate, 'YYYY-MM-DD HH24:MI:SS');
   RETURN 1;
EXCEPTION
   WHEN OTHERS
   THEN
      RETURN 0;
END;
/
