//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMPS3106.Wcf31021 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpRequest", Namespace="http://schemas.datacontract.org/2004/07/VoiceCyber.UMP.Common31021")]
    [System.SerializableAttribute()]
    public partial class UpRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ListByteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private VoiceCyber.UMP.Common.SessionInfo SessionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SvPathField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] ListByte {
            get {
                return this.ListByteField;
            }
            set {
                if ((object.ReferenceEquals(this.ListByteField, value) != true)) {
                    this.ListByteField = value;
                    this.RaisePropertyChanged("ListByte");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public VoiceCyber.UMP.Common.SessionInfo Session {
            get {
                return this.SessionField;
            }
            set {
                if ((object.ReferenceEquals(this.SessionField, value) != true)) {
                    this.SessionField = value;
                    this.RaisePropertyChanged("Session");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SvPath {
            get {
                return this.SvPathField;
            }
            set {
                if ((object.ReferenceEquals(this.SvPathField, value) != true)) {
                    this.SvPathField = value;
                    this.RaisePropertyChanged("SvPath");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.voicecyber.com/UMP/Services/2015/03", ConfigurationName="Wcf31021.IService31021")]
    public interface IService31021 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.voicecyber.com/UMP/Services/2015/03/IService31021/DoOperation", ReplyAction="http://www.voicecyber.com/UMP/Services/2015/03/IService31021/DoOperationResponse")]
        VoiceCyber.UMP.Communications.WebReturn DoOperation(VoiceCyber.UMP.Communications.WebRequest webRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.voicecyber.com/UMP/Services/2015/03/IService31021/UMPUpOperation", ReplyAction="http://www.voicecyber.com/UMP/Services/2015/03/IService31021/UMPUpOperationRespon" +
            "se")]
        VoiceCyber.UMP.Communications.WebReturn UMPUpOperation(UMPS3106.Wcf31021.UpRequest upRequest);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService31021Channel : UMPS3106.Wcf31021.IService31021, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service31021Client : System.ServiceModel.ClientBase<UMPS3106.Wcf31021.IService31021>, UMPS3106.Wcf31021.IService31021 {
        
        public Service31021Client() {
        }
        
        public Service31021Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service31021Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service31021Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service31021Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public VoiceCyber.UMP.Communications.WebReturn DoOperation(VoiceCyber.UMP.Communications.WebRequest webRequest) {
            return base.Channel.DoOperation(webRequest);
        }
        
        public VoiceCyber.UMP.Communications.WebReturn UMPUpOperation(UMPS3106.Wcf31021.UpRequest upRequest) {
            return base.Channel.UMPUpOperation(upRequest);
        }
    }
}
