//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMPS3603.Wcf36031 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Wcf36031.IService36031")]
    public interface IService36031 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService36031/UmpTaskOperation", ReplyAction="http://tempuri.org/IService36031/UmpTaskOperationResponse")]
        VoiceCyber.UMP.Communications.WebReturn UmpTaskOperation(VoiceCyber.UMP.Communications.WebRequest webRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService36031/UmpTaskOperation", ReplyAction="http://tempuri.org/IService36031/UmpTaskOperationResponse")]
        System.Threading.Tasks.Task<VoiceCyber.UMP.Communications.WebReturn> UmpTaskOperationAsync(VoiceCyber.UMP.Communications.WebRequest webRequest);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService36031Channel : UMPS3603.Wcf36031.IService36031, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service36031Client : System.ServiceModel.ClientBase<UMPS3603.Wcf36031.IService36031>, UMPS3603.Wcf36031.IService36031 {
        
        public Service36031Client() {
        }
        
        public Service36031Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service36031Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service36031Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service36031Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public VoiceCyber.UMP.Communications.WebReturn UmpTaskOperation(VoiceCyber.UMP.Communications.WebRequest webRequest) {
            return base.Channel.UmpTaskOperation(webRequest);
        }
        
        public System.Threading.Tasks.Task<VoiceCyber.UMP.Communications.WebReturn> UmpTaskOperationAsync(VoiceCyber.UMP.Communications.WebRequest webRequest) {
            return base.Channel.UmpTaskOperationAsync(webRequest);
        }
    }
}
