//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMPS3104.Wcf31041 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Wcf31041.IService31041")]
    public interface IService31041 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService31041/UMPClientOperation", ReplyAction="http://tempuri.org/IService31041/UMPClientOperationResponse")]
        VoiceCyber.UMP.Communications.WebReturn UMPClientOperation(VoiceCyber.UMP.Communications.WebRequest webRequest);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService31041Channel : UMPS3104.Wcf31041.IService31041, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service31041Client : System.ServiceModel.ClientBase<UMPS3104.Wcf31041.IService31041>, UMPS3104.Wcf31041.IService31041 {
        
        public Service31041Client() {
        }
        
        public Service31041Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service31041Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service31041Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service31041Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public VoiceCyber.UMP.Communications.WebReturn UMPClientOperation(VoiceCyber.UMP.Communications.WebRequest webRequest) {
            return base.Channel.UMPClientOperation(webRequest);
        }
    }
}
