//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMPS3602.Wcf36021 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Wcf36021.IService36021")]
    public interface IService36021 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService36021/UmpTaskOperation", ReplyAction="http://tempuri.org/IService36021/UmpTaskOperationResponse")]
        VoiceCyber.UMP.Communications.WebReturn UmpTaskOperation(VoiceCyber.UMP.Communications.WebRequest webRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService36021/UmpUpOperation", ReplyAction="http://tempuri.org/IService36021/UmpUpOperationResponse")]
        VoiceCyber.UMP.Communications.WebReturn UmpUpOperation(Common3602.UpRequest upRequest);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService36021Channel : UMPS3602.Wcf36021.IService36021, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service36021Client : System.ServiceModel.ClientBase<UMPS3602.Wcf36021.IService36021>, UMPS3602.Wcf36021.IService36021 {
        
        public Service36021Client() {
        }
        
        public Service36021Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service36021Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service36021Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service36021Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public VoiceCyber.UMP.Communications.WebReturn UmpTaskOperation(VoiceCyber.UMP.Communications.WebRequest webRequest) {
            return base.Channel.UmpTaskOperation(webRequest);
        }
        
        public VoiceCyber.UMP.Communications.WebReturn UmpUpOperation(Common3602.UpRequest upRequest) {
            return base.Channel.UmpUpOperation(upRequest);
        }
    }
}
