//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMPS5102.Wcf51021 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Wcf51021.IService51021")]
    public interface IService51021 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService51021/UmpTaskOperation", ReplyAction="http://tempuri.org/IService51021/UmpTaskOperationResponse")]
        VoiceCyber.UMP.Communications.WebReturn UmpTaskOperation(VoiceCyber.UMP.Communications.WebRequest webRequest);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService51021Channel : UMPS5102.Wcf51021.IService51021, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service51021Client : System.ServiceModel.ClientBase<UMPS5102.Wcf51021.IService51021>, UMPS5102.Wcf51021.IService51021 {
        
        public Service51021Client() {
        }
        
        public Service51021Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service51021Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service51021Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service51021Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public VoiceCyber.UMP.Communications.WebReturn UmpTaskOperation(VoiceCyber.UMP.Communications.WebRequest webRequest) {
            return base.Channel.UmpTaskOperation(webRequest);
        }
    }
}
