//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18063
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMPS3102.Wcf31021 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.voicecyber.com/UMP/Services/2015/03", ConfigurationName="Wcf31021.IService31021")]
    public interface IService31021 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.voicecyber.com/UMP/Services/2015/03/IService31021/DoOperation", ReplyAction="http://www.voicecyber.com/UMP/Services/2015/03/IService31021/DoOperationResponse")]
        VoiceCyber.UMP.Communications.WebReturn DoOperation(VoiceCyber.UMP.Communications.WebRequest webRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.voicecyber.com/UMP/Services/2015/03/IService31021/UMPUpOperation", ReplyAction="http://www.voicecyber.com/UMP/Services/2015/03/IService31021/UMPUpOperationRespon" +
            "se")]
        VoiceCyber.UMP.Communications.WebReturn UMPUpOperation(VoiceCyber.UMP.Common31021.UpRequest upRequest);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService31021Channel : UMPS3102.Wcf31021.IService31021, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service31021Client : System.ServiceModel.ClientBase<UMPS3102.Wcf31021.IService31021>, UMPS3102.Wcf31021.IService31021 {
        
        public Service31021Client() {
        }
        
        public Service31021Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service31021Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service31021Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service31021Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public VoiceCyber.UMP.Communications.WebReturn DoOperation(VoiceCyber.UMP.Communications.WebRequest webRequest) {
            return base.Channel.DoOperation(webRequest);
        }
        
        public VoiceCyber.UMP.Communications.WebReturn UMPUpOperation(VoiceCyber.UMP.Common31021.UpRequest upRequest) {
            return base.Channel.UMPUpOperation(upRequest);
        }
    }
}
