//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMPS1102.Wcf11021 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Wcf11021.IService11021")]
    public interface IService11021 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService11021/URPOperation", ReplyAction="http://tempuri.org/IService11021/URPOperationResponse")]
        VoiceCyber.UMP.Communications.WebReturn URPOperation(VoiceCyber.UMP.Communications.WebRequest webRequest);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService11021Channel : UMPS1102.Wcf11021.IService11021, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service11021Client : System.ServiceModel.ClientBase<UMPS1102.Wcf11021.IService11021>, UMPS1102.Wcf11021.IService11021 {
        
        public Service11021Client() {
        }
        
        public Service11021Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service11021Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service11021Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service11021Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public VoiceCyber.UMP.Communications.WebReturn URPOperation(VoiceCyber.UMP.Communications.WebRequest webRequest) {
            return base.Channel.URPOperation(webRequest);
        }
    }
}
