//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMPS6101.Wcf61012 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Wcf61012.IService61012")]
    public interface IService61012 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService61012/UMPReportOperation", ReplyAction="http://tempuri.org/IService61012/UMPReportOperationResponse")]
        VoiceCyber.UMP.Communications.WebReturn UMPReportOperation(VoiceCyber.UMP.Communications.WebRequest webRequest);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService61012Channel : UMPS6101.Wcf61012.IService61012, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service61012Client : System.ServiceModel.ClientBase<UMPS6101.Wcf61012.IService61012>, UMPS6101.Wcf61012.IService61012 {
        
        public Service61012Client() {
        }
        
        public Service61012Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service61012Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service61012Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service61012Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public VoiceCyber.UMP.Communications.WebReturn UMPReportOperation(VoiceCyber.UMP.Communications.WebRequest webRequest) {
            return base.Channel.UMPReportOperation(webRequest);
        }
    }
}
